# Generated by Django 5.2.4 on 2025-10-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_agentinvite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentInvite',
        ),
    ]
