# Generated by Django 5.2.4 on 2025-10-31 22:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_agentinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='amount_in_hand',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
