# Generated by Django 5.2.4 on 2025-10-19 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.agentprofile'),
        ),
        migrations.DeleteModel(
            name='AgentProfile',
        ),
    ]
