# Generated by Django 5.2.4 on 2025-10-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_customer_agent_delete_agentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('duration_days', models.PositiveIntegerField(default=20)),
            ],
        ),
    ]
