# Generated by Django 5.2.4 on 2025-10-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loansettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
