# Generated by Django 5.2.4 on 2025-10-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_last_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='days_paid',
            field=models.IntegerField(default=0),
        ),
    ]
