# Generated by Django 5.2.4 on 2025-10-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_days_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
