# Generated by Django 5.2.4 on 2025-10-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_customer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_score',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='has_active_loan',
            field=models.BooleanField(default=False),
        ),
    ]
