# Generated by Django 5.2.4 on 2025-10-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_customer_credit_score_customer_has_active_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansettings',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='min_loan_amount',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
    ]
