# Generated by Django 5.2.4 on 2025-10-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0009_loansettings_max_loan_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.agentprofile'),
        ),
    ]
