# Generated by Django 5.2.4 on 2025-11-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_admintransactionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
