# Generated by Django 5.2.4 on 2025-11-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_publicholiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicholiday',
            old_name='date',
            new_name='holiday_date',
        ),
        migrations.AlterField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
