# Generated by Django 5.2.4 on 2025-11-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_companyfinance_adminnotification_financetransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintransactionrequest',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'Withdraw from Agent'), ('send_to_admin', 'Send Money to Admin')], default='withdraw', max_length=20),
        ),
    ]
