# Generated by Django 5.2.4 on 2026-01-05 18:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_admintransactionrequest_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_score',
            field=models.IntegerField(default=Decimal('4000.00')),
        ),
        migrations.AlterField(
            model_name='loansettings',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loansettings',
            name='min_loan_amount',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
