# Generated by Django 5.2.4 on 2026-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_alter_customer_credit_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_score',
            field=models.IntegerField(default=500),
        ),
    ]
