# Generated by Django 5.2.4 on 2026-01-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_alter_customer_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_score',
            field=models.IntegerField(default=1000),
        ),
    ]
