# Generated by Django 5.2.4 on 2026-01-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0018_alter_customer_credit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='last_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
