# Generated by Django 5.2.4 on 2026-01-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_loan_last_payment_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repayment',
            unique_together=set(),
        ),
    ]
