# Generated by Django 5.2.4 on 2026-02-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_alter_repayment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
