# Generated by Django 5.2.4 on 2026-04-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agentprofile_amount_in_hand'),
        ('loans', '0025_agentdailyperformance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentdailyperformance',
            name='unique_agent_date_performance',
        ),
        migrations.RenameIndex(
            model_name='agentdailyperformance',
            new_name='loans_agent_agent_i_e301fd_idx',
            old_name='loans_agent_daily_perf_idx',
        ),
        migrations.RenameIndex(
            model_name='agenttransactionlog',
            new_name='loans_agent_agent_i_fc70b0_idx',
            old_name='loans_agent_agent_i_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='loans_custo_agent_i_fd0db7_idx',
            old_name='loans_customer_agent_idx',
        ),
        migrations.RenameIndex(
            model_name='loan',
            new_name='loans_loan_status_962e99_idx',
            old_name='loans_loan_status_idx',
        ),
        migrations.RenameIndex(
            model_name='loan',
            new_name='loans_loan_custome_9efb67_idx',
            old_name='loans_loan_customer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='loan',
            new_name='loans_loan_last_pa_3a4cb5_idx',
            old_name='loans_loan_last_paid_date_idx',
        ),
        migrations.RenameIndex(
            model_name='repayment',
            new_name='loans_repay_loan_id_2ee037_idx',
            old_name='loans_repayment_loan_date_idx',
        ),
        migrations.RenameIndex(
            model_name='repayment',
            new_name='loans_repay_date_c56298_idx',
            old_name='loans_repayment_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='agentdailyperformance',
            unique_together={('agent', 'date')},
        ),
    ]
