# Generated by Django 6.0.6 on 2026-06-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_remove_agentdailyperformance_unique_agent_date_performance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='display_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
