# Generated by Django 6.0.7 on 2026-08-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0027_add_display_order_to_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='AILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('user_role', models.CharField(blank=True, default='', max_length=30)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('cache_hit', models.BooleanField(default=False)),
                ('tool_used', models.CharField(blank=True, default='', max_length=100)),
                ('intent', models.CharField(blank=True, default='', max_length=100)),
                ('response_time', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='loans_ailog_feature_af87c8_idx')],
            },
        ),
    ]
