# Generated by Django 5.1.4 on 2026-08-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_agentprofile_amount_in_hand'),
        ('loans', '0028_ailog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingLoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, default=200.0, max_digits=12)),
                ('ai_suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ai_risk', models.CharField(blank=True, default='', max_length=20)),
                ('ai_confidence', models.IntegerField(blank=True, null=True)),
                ('ai_explanation', models.TextField(blank=True, default='')),
                ('ai_reasons', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.agentprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_applications', to='loans.customer')),
            ],
        ),
    ]
